<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Reqnroll.xUnit.v3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="AngleSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CommissionCalculator.Web\CommissionCalculator.Web.csproj" />
  </ItemGroup>
</Project>
